spring:
#  config:
#    activate:
#      on-profile: docker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.203.196.67:3306/bookecho?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
        max-page-size: 2000
  sql:
    init.mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

zero:
  jwt-key: "/DzESABcaEQWeLCUA73bjlX0Jp/jMUf9rQcECh5QqtQ="